### ISSUE TITLE
Python 3 support - NameError: name 'basestring' is not defined

### ISSUE THREAD

**Issue by CambridgeMBN** [iron-io/iron_cache_python#10]
I get the following error

```File "/home/user/virtualenv/lib/python3.4/site-packages/iron_cache.py", line 117, in put
    if not isinstance(value, basestring) and not isinstance(value,
NameError: name 'basestring' is not defined```

when I try to PUT a key:

```
def put(self, key, value, cache=None, options={}):
      ...
       if not isinstance(value, basestring) and not isinstance(value,
                (int, long)): 
            value = json.dumps(value)

       ...
```

Should `basestring` [be replaced with] (http://stackoverflow.com/a/1979107) `str`?

**Comment by ulandj** [comment]
Hi @CambridgeMBN ,
You have old version of iron_cache client lib. Please install it by cloning from here or with `pip install iron_cashe`. The issue was resolved here: https://github.com/iron-io/iron_cache_python/pull/6

Thanks!

**Comment by CambridgeMBN** [comment]
I pulled the package straight from pip, so you might want to update that too. Thanks for letting me know.
